enum DownloadStatus { queued, downloading, completed, failed }

class DownloadGroup { const DownloadGroup({required this.id, required this.name, required this.createdAt}); final String id; final String name; final int createdAt; Map<String, dynamic> toJson() => {'id': id, 'name': name, 'createdAt': createdAt}; factory DownloadGroup.fromJson(Map<String, dynamic> json) => DownloadGroup(id: json['id'] as String? ?? '', name: json['name'] as String? ?? '', createdAt: json['createdAt'] as int? ?? 0); }
class DownloadTask { const DownloadTask({required this.id, required this.videoCode, required this.title, required this.groupId, required this.quality, required this.status, required this.progress, required this.downloadedBytes, required this.totalBytes, required this.createdAt, required this.updatedAt, this.coverUrl, this.localVideoPath, this.localCoverPath, this.localMetaPath, this.localCommentPath, this.errorMessage}); final String id; final String videoCode; final String title; final String? coverUrl; final String groupId; final String quality; final DownloadStatus status; final double progress; final int downloadedBytes; final int totalBytes; final String? localVideoPath; final String? localCoverPath; final String? localMetaPath; final String? localCommentPath; final String? errorMessage; final int createdAt; final int updatedAt;
  DownloadTask copyWith({DownloadStatus? status, double? progress, int? downloadedBytes, int? totalBytes, String? localVideoPath, String? localCoverPath, String? localMetaPath, String? localCommentPath, String? errorMessage, bool clearError = false}) => DownloadTask(id: id, videoCode: videoCode, title: title, coverUrl: coverUrl, groupId: groupId, quality: quality, status: status ?? this.status, progress: progress ?? this.progress, downloadedBytes: downloadedBytes ?? this.downloadedBytes, totalBytes: totalBytes ?? this.totalBytes, localVideoPath: localVideoPath ?? this.localVideoPath, localCoverPath: localCoverPath ?? this.localCoverPath, localMetaPath: localMetaPath ?? this.localMetaPath, localCommentPath: localCommentPath ?? this.localCommentPath, errorMessage: clearError ? null : errorMessage ?? this.errorMessage, createdAt: createdAt, updatedAt: DateTime.now().millisecondsSinceEpoch);
  Map<String, dynamic> toJson() => {'id': id, 'videoCode': videoCode, 'title': title, 'coverUrl': coverUrl, 'groupId': groupId, 'quality': quality, 'status': status.name, 'progress': progress, 'downloadedBytes': downloadedBytes, 'totalBytes': totalBytes, 'localVideoPath': localVideoPath, 'localCoverPath': localCoverPath, 'localMetaPath': localMetaPath, 'localCommentPath': localCommentPath, 'errorMessage': errorMessage, 'createdAt': createdAt, 'updatedAt': updatedAt}..removeWhere((key, value) => value == null);
  factory DownloadTask.fromJson(Map<String, dynamic> json) => DownloadTask(id: json['id'] as String? ?? '', videoCode: json['videoCode'] as String? ?? '', title: json['title'] as String? ?? '', coverUrl: json['coverUrl'] as String?, groupId: json['groupId'] as String? ?? 'default', quality: json['quality'] as String? ?? '', status: DownloadStatus.values.where((value) => value.name == json['status']).firstOrNull ?? DownloadStatus.queued, progress: (json['progress'] as num?)?.toDouble() ?? 0, downloadedBytes: json['downloadedBytes'] as int? ?? 0, totalBytes: json['totalBytes'] as int? ?? 0, localVideoPath: json['localVideoPath'] as String?, localCoverPath: json['localCoverPath'] as String?, localMetaPath: json['localMetaPath'] as String?, localCommentPath: json['localCommentPath'] as String?, errorMessage: json['errorMessage'] as String?, createdAt: json['createdAt'] as int? ?? 0, updatedAt: json['updatedAt'] as int? ?? 0);
}
extension<T> on Iterable<T> { T? get firstOrNull => isEmpty ? null : first; }
